#Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=admin


spring.datasource.hikari.maximum-pool-size=4
spring.jpa.database-platform=postgres
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true




spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#SHOW-SQL
#spring.jpa.properties.hibernate.show_sql = true
#spring.jpa.show-sql=true


#Sessions
server.servlet.session.timeout=40m



#Security
spring.application.name=spring-security-maven
spring.security.user.roles=USER,ADMIN

#OAuth2
# logging.level.org.springframework.security=TRACE
# logging.level.org.springframework.security.oauth2=DEBUG
#Github
spring.security.oauth2.client.registration.github.client-id=Ov23liKJWJZwkxDhN1DT
spring.security.oauth2.client.registration.github.client-secret=60ad8f4d2894a8c6de02672c29f84b6da67f3727
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.scope=user:email,user:password

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id

#spring.security.oauth2.client.registration.github.scope=email,password
#spring.security.oauth2.client.registration.github.redirect-uri=/login
#spring.security.basic.disabled=true

#Google
spring.security.oauth2.client.registration.google.client-id=736669461120-st2r6remldr96hcvkc0onb9b1fn6bgub.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


spring.security.user.name=admin
spring.security.user.password=admin


server.error.whitelabel.enabled=false
server.error.path=/error